= Java Code Generator Annotations

:TEMPLATE:         pass:quotes[link:./java-code-gen/src/main/java/com/kt/codegen/Template.java[`@Template`]]
:CODE_TRANSFORMER: pass:quotes[link:./java-code-gen/src/main/java/com/kt/codegen/CodeTransformer.java[`@CodeTransformer`]]
:REPLACE:          pass:quotes[link:./java-code-gen/src/main/java/com/kt/codegen/Replace.java[`@Replace`]]]
:SRC_DIR:          ../../java-code-gen-demo/src/main/java/com/kt/codegen/demo
:GEN_DIR:          ../../java-code-gen-demo/target/generated-sources/annotations/com/kt/codegen/demo


== TL;DR
This library provides the following code-generating annotations:

* The {TEMPLATE}
  annotation generates concrete instantiates of generic types analogous
  to C++ templates
* The {CODE_TRANSFORMER}
  annotation can perform arbitrary code transformation using regex string replacements


== C++ Template Emulation

=== First Steps

Consider the following generic class (which, of course, would require a lot more work
before it's a reasonable list implementation):
[source,java]
----
package com.kt.codegen.demo.list1;

class MyList<T> {
    private T[] array;

    MyList(int size) {
        this.array = (T[]) new Object[size];
    }

    T get(int index) {
        return array[index];
    }
}
----

You can annotate it with {TEMPLATE} to e.g. create a concrete String instantiation,
analogous to C++ templates:
[source,java]
----
package com.kt.codegen.demo.list2;

import com.kt.codegen.Instantiate;
import com.kt.codegen.Template;

@Template(@Instantiate(String.class))
class MyList<T> {
    private T[] array;

    MyList(int size) {
        this.array = (T[]) new Object[size];
    }

    T get(int index) {
        return array[index];
    }
}
----

This will generate the following class:
[source,java]
----
// generated from com.kt.codegen.demo.list2.MyList
package com.kt.codegen.demo.list2;

class MyListString {
    private String[] array;

    MyListString(int size) {
        this.array = (String[]) new Object[size];
    }

    String get(int index) {
        return array[index];
    }
}
----
Nice! However, the `(String[]) new Object[size]` expression doesn't make much sense.
Can we do better? Yes, with a custom string replacement, see below.


=== Custom String Replacements
Simply replacing a generic type with a concrete type like we just did doesn't usually
get us all the way, but fret not, there are custom string replacements:
[source,java]
----
package com.kt.codegen.demo.list3;

import com.kt.codegen.Instantiate;
import com.kt.codegen.Replace;
import com.kt.codegen.Template;

@Template(
    @Instantiate(value = String.class,
                 replace = @Replace(from = "(T[]) new Object[size]", to = "new String[size]"))
)
class MyList<T> {
    private T[] array;

    MyList(int size) {
        this.array = (T[]) new Object[size];
    }

    T get(int index) {
        return array[index];
    }
}
----

And our list compiles:
[source,java]
----
// generated from com.kt.codegen.demo.list3.MyList
package com.kt.codegen.demo.list3;

class MyListString {
    private String[] array;

    MyListString(int size) {
        this.array = new String[size];
    }

    String get(int index) {
        return array[index];
    }
}
----


=== Primitives
How about adding a primitive version  our list? Easy, just specify the `double` type
on top:
[source,java]
----
package com.kt.codegen.demo.list4;

import com.kt.codegen.Instantiate;
import com.kt.codegen.Replace;
import com.kt.codegen.Template;

@Template({
    @Instantiate(value = String.class,
                 replace = @Replace(from = "(T[]) new Object[size]", to = "new String[size]")),
    @Instantiate(value = double.class,
                 replace = @Replace(from = "(T[]) new Object[size]", to = "new double[size]"))
})
class MyList<T> {
    private T[] array;

    MyList(int size) {
        this.array = (T[]) new Object[size];
    }

    T get(int index) {
        return array[index];
    }
}
----

which produces `MyListString` from above plus the following class:
[source,java]
----
// generated from com.kt.codegen.demo.list4.MyList
package com.kt.codegen.demo.list4;

class MyListDouble {
    private double[] array;

    MyListDouble(int size) {
        this.array = new double[size];
    }

    double get(int index) {
        return array[index];
    }
}
----


=== Multiple Type Parameters
If your generic class has more than one type parameter then you'll simply have to provide
the necessary number of concrete types for each instantiation:
[source,java]
----
package com.kt.codegen.demo.map;

import com.kt.codegen.Instantiate;
import com.kt.codegen.Template;

import java.time.Instant;

@Template(@Instantiate({String.class, Instant.class }))  // <-- two concrete types
class MyMap<K, V> {                                      // <-- two type parameters
    // ...
}
----


=== Options
The following options allow for more flexibility:

* {TEMPLATE}

  ** For projects that don't follow the maven directory layout you can specify the relative
     source folder with `relativeSourceDir`.
  ** I you prefer prepending the type to the class rather than the default appending variant
     (i.e., `StringMyList` rather than `MyListString` in the example above) then
     you can change `typeNamePosition`.

* {REPLACE}

  ** If normal string replacement won't cut it you can set `regex` to
     `true`.



== Code Transformer
If you want to generate derived versions of a class but template instantiation is not the
right tool for the job, then the more generic
{CODE_TRANSFORMER}
might do the trick.

Say you have a custom primitive list that you have implemented for `double`:
[source,java]
----
package com.kt.codegen.demo.double1;

public class MyDoubleList {
    private double[] array;

    MyDoubleList(int size) {
        this.array = new double[size];
    }

    // ...
}
----

Now, instead of copying and pasting this code a handful of times to create equivalent
implementations for other primitive types (which is both cumbersome and error-prone) you
can do the following instead:

[source,java]
----
package com.kt.codegen.demo.double2;

import com.kt.codegen.CodeTransformer;
import com.kt.codegen.Replace;
import com.kt.codegen.Transform;

@CodeTransformer({
    @Transform(target = "MyFloatList", replace = @Replace(from = "\\bdouble\\b", to = "float", regex = true)),
    @Transform(target = "MyLongList", replace = @Replace(from = "\\bdouble\\b", to = "long", regex = true))
})
public class MyDoubleList {
    private double[] array;

    MyDoubleList(int size) {
        this.array = new double[size];
    }

    // ...
}
----

This will generate two classes:
[source,java]
----
// generated from com.kt.codegen.demo.double2.MyDoubleList
package com.kt.codegen.demo.double2;

public class MyFloatList {
    private float[] array;

    MyFloatList(int size) {
        this.array = new float[size];
    }

    // ...
}
----

And:

[source,java]
----
// generated from com.kt.codegen.demo.double2.MyDoubleList
package com.kt.codegen.demo.double2;

public class MyLongList {
    private long[] array;

    MyLongList(int size) {
        this.array = new long[size];
    }

    // ...
}
----
