= Java Code Generator Annotations

:INSTANTIATE:       pass:quotes[link:java-code-gen/src/main/java/com/kt/codegen/Instantiate.java[`@Instantiate`]]
:DERIVE:            pass:quotes[link:java-code-gen/src/main/java/com/kt/codegen/Derive.java[`@Derive`]]
:REPLACE:           pass:quotes[link:java-code-gen/src/main/java/com/kt/codegen/Replace.java[`@Replace`]]
:SOURCE_DIRECTORY:  pass:quotes[link:java-code-gen/src/main/java/com/kt/codegen/SourceDirectory.java[`@SourceDirectory`]]
:SRC_DIR:           ../main/java/com/kt/codegen/demo
:GEN_DIR:           ../../target/generated-sources/annotations/com/kt/codegen/demo


== TL;DR
=== What is this?
This library provides the following code-generating annotations:

* {INSTANTIATE} generates concrete instantiations of
generic classes analogous to C++ templates, e.g. `MyListString` from
`MyList<T>`
* {DERIVE} generates new classes derived from existing ones by applying
  string or regex replacements to the source code

=== Why should I use it?
The main advantage of this library over generic template engines such as
link:https://www.stringtemplate.org/[StringTemplate],
link:https://velocity.apache.org/[Velocity]
or
link:https://freemarker.apache.org/[FreeMaker] is:

*Your template is actual code*.

Thus, instead of having to write a placeholder-sprinkled, engine-specific
template file, your "template" is a normal Java class with annotations.
The benefits are as follows:

  ** The "template" is running code rather than some resource file
  ** The "template" can be unit tested
  ** The "template" enjoys IDE syntax highlighting - no template
     engine-specific plugins required
  ** The "template" can be auto-formatted, linted and refactored by your IDE


== Instantiate generic classes with {INSTANTIATE}

=== Motivation

Consider the following generic class (which, of course, would require a lot more work
before it's a reasonable list implementation):
[source,java]
----
include::{SRC_DIR}/list1/MyList.java[]
----

You can annotate it with {INSTANTIATE} to e.g. create a concrete String instantiation,
analogous to C++ templates:
[source,java]
----
include::{SRC_DIR}/list2/MyList.java[]
----

This will generate the following class:
[source,java]
----
include::{GEN_DIR}/list2/MyListString.java[]
----

Nice, but the annotation processor only operates on a source code level and simply
replaces occurrences of `T` with `String`. This leads to a guaranteed class cast
exception in the expression `(String[]) new Object[size]`. Can we fix this? Yes, with custom
string replacements, see below.


=== Custom String Replacements
Simply replacing a generic type with a concrete type like we just did doesn't usually
get us all the way, but fret not, there are custom string replacements:
[source,java]
----
include::{SRC_DIR}/list3/MyList.java[]
----

And our list compiles:
[source,java]
----
include::{GEN_DIR}/list3/MyListString.java[]
----

If simple string replacement won't do the trick you set `@Replace(..., regex = true)` for
matching regular expressions.

Also, you can specify multiple replacements with
`replace = {@Replace(...), @Replace(...), ...}`.


=== Primitives
How about adding a primitive version of our list? Simple: just add a `double` instantiation:
[source,java]
----
include::{SRC_DIR}/list4/MyList.java[]
----

This will additionally geenrate the following class:
[source,java]
----
include::{GEN_DIR}/list4/MyListDouble.java[]
----

Note that the class is called `MyListDouble` instead of `MyListdouble` (note the
different case of the "d") to make the two types  explicit in the class name.


=== Multiple Type Parameters
If your generic class has more than one type parameter then you'll simply have to provide
the necessary number of concrete types for each instantiation:
[source,java]
----
include::{SRC_DIR}/map/MyMap.java[]
----


=== Notes
* For projects that don't follow the Maven directory layout you can specify the relative
  source directory with {SOURCE_DIRECTORY} on the source class.
* If normal string replacement won't cut it, you can set `{REPLACE}.regex` to `true`.


== Generate derived classes with {DERIVE}
Say you are working on a primitive collection library, and you have successfully written
a `double` list implementation:
[source,java]
----
include::{SRC_DIR}/double1/MyDoubleList.java[]
----

Now you have a couple of options to create lists for other primitive types:

. You copy and paste the class a couple of times followed by a search/replace frenzy. This
is cumbersome, time-consuming and will eventually lead to implementations drifting
apart because you'll forget to apply that one fix to the `float` implementation.

. You fire up a generic template engine, convert this nice, working, unit-tested,
syntax-highlighted, auto-formatted, error-checked class into a template text
file that immediately loses all those nice properties, and you start configuring
that template engine.

. You annotate your class as follows:

[source,java]
----
include::{SRC_DIR}/double2/MyDoubleList.java[]
----

This will generate two derived classes:
[source,java]
----
include::{GEN_DIR}/double2/MyFloatList.java[]
----

And:

[source,java]
----
include::{GEN_DIR}/double2/MyLongList.java[]
----

=== Notes

* The relative source directory can also be changed using {SOURCE_DIRECTORY}.
* I you prefer prepending the concrete type(s) to the class rather than the default
  appending style (i.e., `StringMyList` rather than `MyListString`) then set
  `{INSTANTIATE}.append` to `false`.
* Custom string replacements can be specified in `{INSTANTIATE}.replace`.
