package com.kt.template;


import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;


/**
 * A source code generator that generates new classes by performing regular expression string replacements.
 * <p/>
 *
 * Classes can be generated by supplying to one of the replacement parameters ({@link #t1} through {@link #t10})
 * a string array containing the following information:
 * <ol>
 *     <li>A fully qualified target class name</li>
 *     <li>A sequence of ([from], [to]) pairs of regex string replacements</li>
 * </ol>
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface CodeTransformer {
    /**
     * The source directory relative to the classpath where <code>.class</code> files are residing. Defaults
     * to Maven's <code>../../src/main/java</code>, i.e., up two levels from <code>target/classes/</code>
     * and then down to <code>src/main/java</code>
     */
    String relativeSourceDir() default "../../src/main/java";

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t1() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t2() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t3() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t4() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t5() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t6() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t7() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t8() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t9() default {};

    /** A target class code generation setup, see {@link CodeTransformer}. */
    String[] t10() default {};
}
